# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/rameshdas/Desktop/Music Player Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/rameshdas/Desktop/Music Player Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake /Users/rameshdas/Desktop/Music\ Player\ Project/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/rameshdas/Desktop/Music Player Project/CMakeFiles" "/Users/rameshdas/Desktop/Music Player Project//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/rameshdas/Desktop/Music Player Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MusicPlayer

# Build rule for target.
MusicPlayer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MusicPlayer
.PHONY : MusicPlayer

# fast build rule for target.
MusicPlayer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/build
.PHONY : MusicPlayer/fast

src/AudioEngine.o: src/AudioEngine.cpp.o
.PHONY : src/AudioEngine.o

# target to build an object file
src/AudioEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/AudioEngine.cpp.o
.PHONY : src/AudioEngine.cpp.o

src/AudioEngine.i: src/AudioEngine.cpp.i
.PHONY : src/AudioEngine.i

# target to preprocess a source file
src/AudioEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/AudioEngine.cpp.i
.PHONY : src/AudioEngine.cpp.i

src/AudioEngine.s: src/AudioEngine.cpp.s
.PHONY : src/AudioEngine.s

# target to generate assembly for a file
src/AudioEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/AudioEngine.cpp.s
.PHONY : src/AudioEngine.cpp.s

src/GUI.o: src/GUI.cpp.o
.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i
.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s
.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

vendor/imgui/backends/imgui_impl_sdl2.o: vendor/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
vendor/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_sdl2.cpp.o

vendor/imgui/backends/imgui_impl_sdl2.i: vendor/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
vendor/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_sdl2.cpp.i

vendor/imgui/backends/imgui_impl_sdl2.s: vendor/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
vendor/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_sdl2.cpp.s

vendor/imgui/backends/imgui_impl_sdlrenderer2.o: vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_sdlrenderer2.o

# target to build an object file
vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.o

vendor/imgui/backends/imgui_impl_sdlrenderer2.i: vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_sdlrenderer2.i

# target to preprocess a source file
vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.i

vendor/imgui/backends/imgui_impl_sdlrenderer2.s: vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_sdlrenderer2.s

# target to generate assembly for a file
vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_demo.o: vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.cpp.o

vendor/imgui/imgui_demo.i: vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.cpp.i

vendor/imgui/imgui_demo.s: vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_tables.o: vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.cpp.o

vendor/imgui/imgui_tables.i: vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.cpp.i

vendor/imgui/imgui_tables.s: vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MusicPlayer.dir/build.make CMakeFiles/MusicPlayer.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... MusicPlayer"
	@echo "... src/AudioEngine.o"
	@echo "... src/AudioEngine.i"
	@echo "... src/AudioEngine.s"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... vendor/imgui/backends/imgui_impl_sdl2.o"
	@echo "... vendor/imgui/backends/imgui_impl_sdl2.i"
	@echo "... vendor/imgui/backends/imgui_impl_sdl2.s"
	@echo "... vendor/imgui/backends/imgui_impl_sdlrenderer2.o"
	@echo "... vendor/imgui/backends/imgui_impl_sdlrenderer2.i"
	@echo "... vendor/imgui/backends/imgui_impl_sdlrenderer2.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

